# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 20:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('volunteers_needed', models.IntegerField(blank=True, null=True)),
                ('volunteers_scheduled', models.IntegerField(blank=True, null=True)),
                ('vehicles_needed', models.IntegerField(blank=True, null=True)),
                ('vehicles_scheduled', models.IntegerField(blank=True, null=True)),
                ('cases_to_deliver', models.IntegerField(blank=True, null=True)),
                ('cases_delivered', models.IntegerField(blank=True, null=True)),
                ('filters_to_deliver', models.IntegerField(blank=True, null=True)),
                ('filters_delivered', models.IntegerField(blank=True, null=True)),
                ('wipes_to_deliver', models.IntegerField(blank=True, null=True)),
                ('wipes_delivered', models.IntegerField(blank=True, null=True)),
                ('vaseline_to_deliver', models.IntegerField(blank=True, null=True)),
                ('vaseline_delivered', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.FloatField(default=-83.6874562)),
                ('latitude', models.FloatField(default=43.0125274)),
                ('persons_in_household', models.IntegerField(blank=True, null=True)),
                ('cases_requested', models.IntegerField(blank=True, null=True)),
                ('filters_requested', models.IntegerField(blank=True, null=True)),
                ('vaseline_requested', models.IntegerField(blank=True, null=True)),
                ('wipes_requested', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('delivery_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DeliveryDate')),
            ],
        ),
        migrations.CreateModel(
            name='HelpOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases_count', models.IntegerField(blank=True, null=True)),
                ('pallets_count', models.IntegerField(blank=True, null=True)),
                ('back_braces_count', models.IntegerField(blank=True, null=True)),
                ('dollies_count', models.IntegerField(blank=True, null=True)),
                ('vaseline_count', models.IntegerField(blank=True, null=True)),
                ('wipes_count', models.IntegerField(blank=True, null=True)),
                ('dollar_donation_amount', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('volunteer_interest', models.IntegerField(blank=True, null=True)),
                ('group_size', models.IntegerField(blank=True, null=True)),
                ('will_unload', models.IntegerField(blank=True, null=True)),
                ('will_deliver', models.IntegerField(blank=True, null=True)),
                ('have_vehicle', models.IntegerField(blank=True, null=True)),
                ('availability', models.TextField(blank=True, null=True)),
                ('park_and_serve_address_in_flint', models.CharField(blank=True, max_length=200, null=True)),
                ('park_and_serve_date_and_time', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(default=1)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=4, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('local', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(default='Flint', max_length=45)),
                ('state', models.CharField(default='MI', max_length=4)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(default='Flint', max_length=45)),
                ('state', models.CharField(default='MI', max_length=4)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.FloatField(default=-83.6874562)),
                ('latitude', models.FloatField(default=43.0125274)),
                ('has_water', models.IntegerField(blank=True, null=True)),
                ('has_volunteers', models.IntegerField(blank=True, null=True)),
                ('has_vehicles_or_drivers', models.IntegerField(blank=True, null=True)),
                ('testers', models.IntegerField(blank=True, null=True)),
                ('has_lifting_supplies', models.IntegerField(blank=True, null=True)),
                ('has_other_supplies', models.IntegerField(blank=True, null=True)),
                ('other_supplies', models.TextField()),
                ('monday_dist', models.CharField(blank=True, max_length=200, null=True)),
                ('tuesday_dist', models.CharField(blank=True, max_length=200, null=True)),
                ('wednesday_dist', models.CharField(blank=True, max_length=200, null=True)),
                ('thursday_dist', models.CharField(blank=True, max_length=200, null=True)),
                ('friday_dist', models.CharField(blank=True, max_length=200, null=True)),
                ('saturday_dist', models.CharField(blank=True, max_length=200, null=True)),
                ('sunday_dist', models.CharField(blank=True, max_length=200, null=True)),
                ('water_case_limit', models.CharField(blank=True, max_length=200, null=True)),
                ('requirements', models.CharField(blank=True, max_length=200, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True, verbose_name='date added')),
                ('notes', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Organization')),
            ],
        ),
        migrations.DeleteModel(
            name='DonationOffer',
        ),
        migrations.DeleteModel(
            name='VolunteerOffer',
        ),
        migrations.DeleteModel(
            name='WaterDeliveryRequest',
        ),
        migrations.DeleteModel(
            name='WaterDonated',
        ),
        migrations.DeleteModel(
            name='WaterReceived',
        ),
    ]
