# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160217_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualhelpoffer',
            name='note_for_recipient',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_vaseline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_wipes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='limits',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='needs_vaseline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='needs_wipes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='pickup_requirements',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
