# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160220_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='individualhelpoffer',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
