# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_individualhelpoffer_other_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='delivery_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.H2OFlintDeliveryDate'),
        ),
    ]
