# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160223_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='recipient_first',
        ),
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='recipient_last',
        ),
    ]
