# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160301_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='action_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='calltime_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='left_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='no_contact',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
