from __future__ import unicode_literals

from django.db import models

class WaterDistributionLocation(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    region = models.CharField(max_length=20)
    long_position = models.DecimalField (max_digits=8, decimal_places=3)
	lat_position = models.DecimalField (max_digits=8, decimal_places=3)
    monday_dist = models.CharField(max_length=200)
    tuesday_dist = models.CharField(max_length=200)
    wednesday_dist = models.CharField(max_length=200)
    thursday_dist = models.CharField(max_length=200)
    friday_dist = models.CharField(max_length=200)
    saturday_dist = models.CharField(max_length=200)
    sunday_dist = models.CharField(max_length=200)
    limits = models.CharField(max_length=200)
    date_added = models.DateTimeField('date added')
    notes = models.TextField()


class WaterDeliveryRequest(models.Model):
    zipcode = models.CharField(max_length=10)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    last_name = models.CharField(max_length=45)
    first_name = models.CharField(max_length=45)
    region = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    long_position = models.DecimalField (max_digits=8, decimal_places=3)
	lat_position = models.DecimalField (max_digits=8, decimal_places=3)
    delivery_date = models.DateTimeField('delivery day')
	delivery_time = models.DateTimeField('delivery time') 
    persons_in_household = models.IntegerField()
    video_url = models.CharField(max_length=20)
    notes = models.TextField()


class WaterReceived(models.Model):
    delivery_date = models.DateTimeField('delivery day')
    zipcode = models.CharField(max_length=10)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    last_name = models.CharField(max_length=45)
    first_name = models.CharField(max_length=45)
    region = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    long_position = models.DecimalField (max_digits=8, decimal_places=3)
	lat_position = models.DecimalField (max_digits=8, decimal_places=3)
    video_url = models.CharField(max_length=20)
    notes = models.TextField()


class WaterDonated(models.Model):
    org_name = models.CharField(max_length=200)
    contact_first_name = models.CharField(max_length=45)
    contact_last_name = models.CharField(max_length=45)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=4)
    zipcode = models.CharField(max_length=10)
    long_position = models.DecimalField (max_digits=8, decimal_places=3)
	lat_position = models.DecimalField (max_digits=8, decimal_places=3)
    number_cases = models.IntegerField()
    number_pallets = models.IntegerField()
    donation_date = models.DateTimeField('delivery day')
    notes = models.TextField()


class DonationOffer(models.Model):
    org_name = models.CharField(max_length=200)
    contact_first_name = models.CharField(max_length=45)
    contact_last_name = models.CharField(max_length=45)
    email = models.CharField(max_length=200)
    contact_person_phone = models.CharField(max_length=20)
	org_phone = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=4)
    zipcode = models.CharField(max_length=10)
    long_position = models.DecimalField (max_digits=8, decimal_places=3)
	lat_position = models.DecimalField (max_digits=8, decimal_places=3)
    number_cases_to_donate = models.IntegerField()
    number_cases_per_household = models.IntegerField()
    number_pallets_to_donate = models.IntegerField()
    volunteers_requested = models.IntegerField()
    other_items_to_donate = models.TextField()
    dollar_donation_amount = models.DecimalField (decimal_places=2)
    delivery_date = models.DateTimeField('delivery day')
    delivery_time = models.DateTimeField('delivery time')
    special_instructions = models.TextField()
    video_url = models.CharField(max_length=20)
    notes = models.TextField()


class VolunteerOffer(models.Model):
    org_name = models.CharField(max_length=200)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=4)
    zipcode = models.CharField(max_length=10)
    long_position = models.DecimalField (max_digits=8, decimal_places=3)
	lat_position = models.DecimalField (max_digits=8, decimal_places=3)
    interests = models.TextField()
    special_skills = models.TextField()
    best_day_and_time = models.TextField()
    notes = models.TextField()



class ServiceQuestionnaire(models.Model):
    zipcode = models.CharField(max_length=10)
    first_time_getting_water = models.IntegerField()
    trips_per_week = models.IntegerField()
	household_weekly_cases = models.IntegerField()
	best_experiences = models.TextField()
	worst_experiences = models.TextField()
	wait_time = models.TextField()
    know_of_others = models.TextField()
    changes = models.TextField()
    video_url = models.CharField(max_length=20)
    notes = models.TextField()